# Generated by Django 5.1.1 on 2024-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeClockin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server', models.CharField(max_length=200)),
                ('clockin', models.BooleanField(default=False)),
            ],
        ),
    ]
