# Generated by Django 5.1.1 on 2024-09-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuSelection', models.CharField(choices=[('1', 'Cheese Burger'), ('2', 'Double Cheese Burger'), ('3', 'Steak Burrito'), ('4', 'Chicken Burrito'), ('5', 'Pepperoni Pizza'), ('6', 'Grilled Chicken Salad')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
