# Generated by Django 5.1.1 on 2024-09-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_mealorder_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeClockin',
        ),
    ]
