# Generated by Django 5.1.1 on 2024-10-14 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_order_orderitem_table_user_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.order'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ManyToManyField(through='TMS.OrderItem', to='TMS.order'),
        ),
    ]
