# Generated by Django 5.1.1 on 2024-10-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_orderitem_item_orderitem_order_remove_item_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
