# Generated by Django 5.1.1 on 2024-10-14 02:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0005_table_chairs_alter_item_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='table',
            name='chairs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
