# Generated by Django 5.1.1 on 2024-10-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0007_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.table')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TMS.table'),
            preserve_default=False,
        ),
    ]
