# Generated by Django 5.1.1 on 2024-10-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0008_table_guests_remove_order_table_tableorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numTables', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TMS.restaurant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TableOrder',
        ),
    ]
