# Generated by Django 5.1.1 on 2024-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TMS', '0008_delete_employees_delete_mealorder_delete_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('1', 'Cheese Burger'), ('2', 'Double Cheese Burger'), ('3', 'Steak Burrito'), ('4', 'Chicken Burrito'), ('5', 'Pepperoni Pizza'), ('6', 'Grilled Chicken Salad')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(choices=[('100', 'Charne Robinson'), ('200', 'Jacob Sparks'), ('300', 'Daryna Kozlova'), ('400', 'Isaiah Dillard'), ('500', 'Anthony Gilliam')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('1', '1- 4 seats'), ('2', '2- 4 seats'), ('3', '3- 4 seats'), ('4', '4- 6 seats'), ('5', '5- 6 seats'), ('6', '6- 6 seats'), ('7', '7- 8 seats'), ('8', '8- 8 seats')], max_length=1)),
            ],
        ),
    ]
