# Generated by Django 5.1.1 on 2024-11-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0009_initial'),
        ('TMS', '0009_restaurant_table_restaurant_delete_tableorder'),
    ]

    operations = [
    ]
