# Generated by Django 5.1.1 on 2024-11-23 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0009_restaurant_table_restaurant_delete_tableorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Host', 'Host'), ('Server', 'Server')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeClockin',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='chairs',
            new_name='seats',
        ),
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved')], default='Available', max_length=30),
        ),
        migrations.AddField(
            model_name='table',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TMS.employee'),
            preserve_default=False,
        ),
    ]
