# Generated by Django 5.1.1 on 2024-11-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0010_merge_20241121_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeClockin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server', models.CharField(max_length=200)),
                ('clockin', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table',
        ),
        migrations.AddField(
            model_name='order',
            name='orderID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='TMS.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='chairs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TMS.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='tableID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='table_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
