# Generated by Django 5.1.1 on 2024-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0010_employee_delete_employeeclockin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ManyToManyField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], through='TMS.OrderItem', to='TMS.order'),
        ),
    ]
