# Generated by Django 5.1.1 on 2024-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0011_alter_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ManyToManyField(through='TMS.OrderItem', to='TMS.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], max_length=30),
        ),
    ]
