# Generated by Django 5.1.1 on 2024-11-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0011_employeeclockin_delete_server_remove_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Host', 'Host'), ('Server', 'Server')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeClockin',
        ),
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='table',
            name='employee',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='TMS.employee'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
