# Generated by Django 5.1.1 on 2024-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0015_table_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.CharField(choices=[('available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved')], default='Available', max_length=30),
        ),
    ]
