# Generated by Django 5.1.1 on 2024-11-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0016_alter_table_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.CharField(choices=[('Available', 'available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved')], default='Available', max_length=30),
        ),
    ]
