# Generated by Django 5.1.1 on 2024-12-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0021_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
