# Generated by Django 5.1.1 on 2024-12-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0026_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.employee'),
        ),
        migrations.AlterField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('rect', 'Rectangle')], default='Rectangle', max_length=30),
        ),
    ]
