# Generated by Django 5.1.1 on 2024-12-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0028_alter_restaurant_numtables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
