# Generated by Django 5.1.1 on 2024-10-11 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0002_delete_order'),
        ('TMS', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('1', 'Cheese Burger'), ('2', 'Double Cheese Burger'), ('3', 'Steak Burrito'), ('4', 'Chicken Burrito'), ('5', 'Pepperoni Pizza'), ('6', 'Grilled Chicken Salad')], max_length=5)),
                ('server', models.CharField(choices=[('100', 'Charne Robinson'), ('200', 'Jacob Sparks'), ('300', 'Daryna Kozlova'), ('400', 'Isaiah Dillard'), ('500', 'Anthony Gilliam')], max_length=5)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatedTable', to='TMS.table')),
            ],
        ),
    ]
