# Generated by Django 5.1.1 on 2024-10-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_initial'),
        ('TMS', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='TMS.order'),
        ),
    ]
