# Generated by Django 5.1.1 on 2024-10-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
