# Generated by Django 5.1.1 on 2024-10-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Server', '0002_delete_server'),
        ('TMS', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(choices=[('100', 'Charne Robinson'), ('200', 'Jacob Sparks'), ('300', 'Daryna Kozlova'), ('400', 'Isaiah Dillard'), ('500', 'Anthony Gilliam')], max_length=5)),
                ('orders', models.ManyToManyField(to='TMS.order')),
                ('tables', models.ManyToManyField(to='TMS.table')),
            ],
        ),
    ]
