# Generated by Django 5.1.1 on 2024-10-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TMS', '0009_initial'),
        ('Table', '0002_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('1', '1- 4 seats'), ('2', '2- 4 seats'), ('3', '3- 4 seats'), ('4', '4- 6 seats'), ('5', '5- 6 seats'), ('6', '6- 6 seats'), ('7', '7- 8 seats'), ('8', '8- 8 seats')], max_length=5)),
                ('server', models.CharField(choices=[('100', 'Charne Robinson'), ('200', 'Jacob Sparks'), ('300', 'Daryna Kozlova'), ('400', 'Isaiah Dillard'), ('500', 'Anthony Gilliam')], max_length=5)),
                ('orders', models.ManyToManyField(to='TMS.order')),
            ],
        ),
    ]
